---
title: "Math for the multivariate-t random effects"
output: pdf_document
---

## Converting Multivariate-normal to Multivariate-t

The code for implementing the Multivariate-t distribution in JAGS and STAN relies on converting the Multivariate-normal distribution, rather than using built in functions.  

The assumption is that two independent random variables are  
$$ z \sim MVN(0, \Sigma )$$ 
$$ s \sim { \chi }_{ \nu  }^{ 2 }(df)$$ 

Then the derived variable,  
$$ y = z \cdot \sqrt { \nu / s } $$

is Multivariate-t with parameters $\Sigma$ and $\nu$. Further details can be found in  
https://en.wikipedia.org/wiki/Multivariate_t-distribution  
https://journal.r-project.org/archive/2013-2/hofert.pdf  

Problems of using the built in Multivariate-t distributions in JAGS and STAN can be found on respective forums,  
JAGS: http://sourceforge.net/p/mcmc-jags/discussion/610037/thread/491d9ccc/?limit=25  
STAN: https://groups.google.com/forum/#!topic/stan-users/0F0O4hfHA8g  

## Treatment of random effects

In all of the applications, we're assuming that a number of knots $k$ is chosen to approximate the spatial field of the data, and the dimension of the knots is less than the number of data points $n$. The vector of random effects at the knots is denoted as $x_{*}$.  

The random effects at the knot locations are multivariate normal, 
$$ x_{*} \sim MVN(0, \Sigma )$$ 
where the covariance matrix $\Sigma_{*}$ is a square matrix ($k by k$) representing the spatial covariance between knots. Elements of $\Sigma_{*}$ are modeled by specifying a covariance function (exponential, Gaussian, Matern, etc) and using the distance between locations. For example, with a Gaussian covariance function,  
$$ { \Sigma_{*} }_{ i,j }={ \sigma  }^{ 2 }\cdot exp\left( -\tau \cdot { d }_{ i,j }^{ 2 } \right)  $$ 
  
where ${ \sigma  }^{ 2 }$ is a scaling parameter, and $\tau$ is a shape parameter, relating the distance between knots ${ d }_{ i,j }$ to covariance.  

The covariance matrix of knots, $\Sigma_{*}$ can be viewed as the block matrix of a larger matrix, relating the covariances between the knots to the covariances between the locations where data are observed. 
  
$$\Sigma =\begin{bmatrix} { \Sigma  }_{ obs } & { \Sigma  }_{ (obs,*) } \\ { \Sigma  }_{ (*,\quad obs) } & { \Sigma  }_{ * } \end{bmatrix}$$
Like above, each element of the covariance matrices are only dependent on the distance between locations, and any estimated parameters.  

## Projecting random effects to observed locations

To project the spatial random effects to the locations where we have observed data (similar to interpolation) We can use the approach of Latimer (2009, Ecol Lett) and others to only use $\Sigma_{*}$ and $\Sigma_{(obs,*)}$

Given a vector of random effects at the knot locations, $x_{*}$, we can project to the data locations using the equation 
$$x_{obs} = { { { { \Sigma  }_{ (obs,*) }^{ \backprime  }\Sigma  }_{ * }^{ -1 } }x }^{ * }$$

And then we can combined those projected random effects $x_{obs}$ with any covariate data at the observed locations to get the total predicted values. 
