---
output:
  pdf_document: default
  html_document: default
---

# Starling example

```{r packages, echo=FALSE, silent=FALSE, warning=FALSE}
library(sp)
library(rgdal)
library(ggplot2)
library(rrfields)
library(rstan)
library(dplyr)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

## Load data

```{r load}

dat = read.csv("/users/eric.ward/downloads/amon-ave.csv", stringsAsFactors = FALSE)
names(dat) = tolower(names(dat))
sites = read.csv("/users/eric.ward/downloads/AMONsites.csv", stringsAsFactors = FALSE)
library(dplyr)

dat = left_join(dat, sites, by = "siteid") %>% filter(!is.na(latitude)) %>% 
  mutate(startmonth = as.numeric(substr(startdate.x,6,7)),
    endmonth = as.numeric(substr(enddate,6,7)),
    year = as.numeric(substr(startdate.x,1,4))) %>% 
  filter(endmonth == startmonth) %>% 
  filter(longitude < -101.6650) %>% 
  filter(conc > 0) %>% 
  as.data.frame()

dat[,"year"] = dat[,"year"] - min(dat[,"year"]) + 1
d = dat

d$ID = seq(1,nrow(d))
coordinates(d) = c("longitude", "latitude")
proj4string(d) <- CRS("+proj=longlat +datum=WGS84")  ## for example
d = as.data.frame(spTransform(d, CRS(paste("+proj=utm +zone=11"," ellps=WGS84",sep=''))))
d$RouteID = as.integer(as.factor(d$siteid))
d$latitude = d$latitude / 100000
d$longitude = d$longitude / 100000
d$time = as.integer(as.factor(paste0(d$year,"-",d$startmonth)))

mvt_gamma = rrfield(conc ~ year + startmonth + I(startmonth^2), data=d, 
  time = "time", lon="longitude", lat="latitude", nknots = 12, 
  obs_error = "gamma", covariance="squared-exponential", 
  prior_gp_sigma = half_t(100, 0, 1), prior_gp_scale = half_t(3, 0, 1), 
  estimate_df =TRUE, estimate_ar = FALSE, algorithm="sampling",
chains = 1L, iter=700, control = list(adapt_delta=0.9))

models[[i]] = mvt_gamma
}

#d[,"Latitude"] = as.numeric(d[,"Latitude"])
#d[,"Longitude"] = as.numeric(d[,"Longitude"])
#d[,"sum"] = as.numeric(d[,"sum"])
#d[,"year"] = as.integer(d[,"year"])
d = d[which(d$AOU=="4930"),] # use only starling data
d = d[which(d$statenum%in%c(33,69,89) & d$year > 1997),] # data from ID, WA, OR

d[,"year"] = d[,"year"] - min(d[,"year"]) + 1

# Project coordinates to UTM using sp()
d$ID = seq(1,nrow(d))
coordinates(d) = c("Longitude", "Latitude")
proj4string(d) <- CRS("+proj=longlat +datum=WGS84")  ## for example
d = as.data.frame(spTransform(d, CRS(paste("+proj=utm +zone=11"," ellps=WGS84",sep=''))))
d$Latitude = d$Latitude/100000
d$Longitude = d$Longitude/100000
# Hold out 10% for test data set
#set.seed(123)
#s = sample(seq(1,nrow(d)), size = floor(nrow(d)*0.1), replace=F)
#holdout = d[s,]
#d = d[-s,]

d$RouteID = as.integer(as.factor(d$Route))
#plot of data
#ggplot(d, aes(Longitude,Latitude,color=log(sum))) + 
# geom_point(alpha=1,size=1) + facet_wrap(~year)
```

## Run model if output doesn't exist, otherwise load workspace

```{r}
fname = "starling_rrfields.Rdata"
runModel = TRUE#!file.exists(fname)
if(runModel) {
  
  # fit model with MVT random field
library(rrfields)

mvt_gamma = rrfield(sum ~ 1, data=d, time = "year", lon="Longitude", lat="Latitude", station = "RouteID", nknots = 30, obs_error = "gamma", covariance="squared-exponential",prior_sigma = half_t(100, 0, 1),
  estimate_df = TRUE, estimate_ar = TRUE, algorithm="sampling", chains = 3L, iter=1000)

# fit model with MVN random field
mvn_gamma = rrfield(sum ~ 1, data=d, time = "year", lon="Longitude", lat="Latitude",
  station = "RouteID", nknots = 30L, obs_error = "gamma", covariance="squared-exponential",
  estimate_df = FALSE, fixed_df_value = 100, estimate_ar = TRUE, fixed_ar_value = 1, algorithm="sampling",
  year_re = FALSE, chains = 3L, iter=1000)

save.image(fname)
}

m= tidy(mvt_gamma2) %>% filter(grepl("y_hat", term))
hist(m$estimate)

if(!runModel) {
  load(fname)
}
```

## Calculate prediction intervals

```{r intervals}
# Plot the predictions from each object to the fitted data
mvt_pred = predict(mvt_gamma, mcmc_draws = 1000,
  conf_level = 0.95, interval = "prediction")
mvn_pred = predict(mvn_gamma, mcmc_draws = 1000,
  conf_level = 0.95, interval = "prediction")

mvt_pred = predict(mvt_gamma, newdata = holdout, mcmc_draws = 1000,
  conf_level = 0.95, interval = "prediction")
mvn_pred = predict(mvn_gamma, newdata = holdout, mcmc_draws = 1000,
  conf_level = 0.95, interval = "prediction")
```


```{r, echo=FALSE, fig.pos="placeHere", fig.cap = "Estimated posterior degrees of freedom for the multivariate-t distribution"}
df=data.frame("x"=extract(mvt_gamma$model)[["df"]])
ggplot(data=df, aes(x=x)) + geom_histogram(alpha=0.5) + xlab("MVT degrees of freedom")
```


```{r, echo=FALSE, fig.pos="placeHere", fig.cap = "Estimated predicted vs observed (blue = mvt)"}
plot(log(mvn_pred$estimate), log(holdout[,"sum"]), col="red",
  pch = 16, cex=0.6, xlab = "Prediction", ylab = "Observed")
points(log(mvt_pred$estimate), log(holdout[,"sum"]), cex=0.8, col="blue")
abline(0,1)
```

```{r, echo=FALSE, fig.pos="placeHere", fig.cap = "Ratio of MVN CI widths : MVT CI widtsh"}

ratio = log((mvn_pred$conf_high - mvn_pred$conf_low) / (mvt_pred$conf_high - mvt_pred$conf_low))

hist(ratio, 40, col="grey", xlab = paste0("MVN CI widths : MVT CI widths"), main="")
```


```{r, echo=FALSE, fig.pos="placeHere", fig.cap = "Estimated year effects"}

mvt_year=extract(mvt_gamma$model)[["yearEffects"]]
mvt_year = data.frame("year"=seq(min(d$year),max(d$year)), 
  "mean"=apply(mvt_year,2,mean), "lower"=apply(mvt_year,2,quantile,0.025),
  "upper"=apply(mvt_year,2,quantile,0.975),"model"="mvt")
mvn_year=extract(mvn_gamma$model)[["yearEffects"]]
mvn_year = data.frame("year"=seq(min(d$year),max(d$year)), 
  "mean"=apply(mvn_year,2,mean), "lower"=apply(mvn_year,2,quantile,0.025),
  "upper"=apply(mvn_year,2,quantile,0.975),"model"="mvn")
mvt_year = rbind(mvt_year,mvn_year)

ggplot(data=mvt_year) + geom_ribbon(aes(x=year,ymin=lower,ymax=upper,
  group=model,fill=model),alpha=0.2) + 
  xlab("Year") + ylab("Estimated year effect")
```

```{r, echo=FALSE,fig.pos="placeHere", fig.cap = "Histogram of raw data and estimated values"}

par(mfrow = c(3,1), mai=c(0.5,0.5,0.1,0.1))
hist(holdout[,"sum"], 40, col="grey", main="Raw", xlab="", ylab="")
hist(mvt_pred$estimate, 40, col="grey", main="MVT", xlab="", ylab="")
hist(mvn_pred$estimate, 40, col="grey", main="MVN", xlab="", ylab="")
```
