---
title: "Comparing MVN and MVT spatial random effects"
output:
  pdf_document:
    fig_caption: yes
---

```{r chunkSet, cache=FALSE, echo=FALSE,warning=FALSE,message=FALSE,results="hide"}
library(cluster)
library(mvtnorm)
library(R2jags)
library(fields)
library(ggplot2)
library(knitr)
library(MASS)
library(rstan)
library(reshape2)
opts_chunk$set(tidy=TRUE, message=FALSE,warning=FALSE)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

```{r}
devtools::install_github("ropensci/rerddap")
library('rerddap')
out = info('erdCalCOFIlrvcntpos')
td = tabledap(out, fields = c('time','longitude', 'latitude', 'larvae_10m2', 'common_name'))

td$month = as.numeric(substr(td$time,6,7))
td$year = as.numeric(substr(td$time,1,4))
td$day = as.numeric(substr(td$time,9,10))
td$jday = date::mdy.date(td$month,td$day,td$year) - date::mdy.date(1,1,td$year)
td$station = paste(td$longitude, td$latitude)

dayweek = expand.grid(day=1:7, week=1:52)
dayweek$jday=1:nrow(dayweek)
td = left_join(td, dayweek[,c("week","jday")])

# create all combos of station-years
stationyr = expand.grid(stationyr = unique(paste(td$station, td$year, sep=":")), common_name = unique(td$common_name))
# extract year and station
stationyr$station = unlist(lapply(strsplit(as.character(stationyr$stationyr),":"), getElement, 1))
stationyr$year = as.numeric(unlist(lapply(strsplit(as.character(stationyr$stationyr),":"), getElement, 2)))
# extract lat and lon to numeric
stationyr$longitude = as.numeric(unlist(lapply(strsplit(as.character(stationyr$station)," "), getElement, 1)))
stationyr$latitude = as.numeric(unlist(lapply(strsplit(as.character(stationyr$station)," "), getElement, 2)))
# drop concatenated stationyr
stationyr = stationyr[,c("common_name","longitude","latitude","year","station")]

# Include zero densities
td = td[,c("longitude","latitude","larvae_10m2","year","station","common_name")]
td$longitude = as.numeric(td$longitude)
td$latitude = as.numeric(td$latitude)
td$larvae_10m2 = as.numeric(td$larvae_10m2)

td = left_join(stationyr, td)
td$larvae_10m2[which(is.na(td$larvae_10m2))] = 0

# create frequency of occurrence table by spp / year
g = group_by(td[td$common_name!="" & td$year < 1966,], year, common_name) %>% 
  summarize(f = length(which(larvae_10m2>0)) / length(larvae_10m2)) %>%
  group_by(common_name) %>% 
  summarize(m = mean(f))



td = td[td$year%in%c(YEARS),]

subsetCalcofi = function(td, SPP, YEARS, MONTHS) {
  

td = td[td$common_name==sort(unique(td$common_name))[SPP],]
td = td[td$year%in%c(YEARS) & td$month%in%c(MONTHS),]

td = left_join(stationyr, td)
td$larvae_10m2[which(is.na(td$larvae_10m2))] = 0
td = td[td$year%in%c(YEARS),]

g = group_by(td, station, year) %>% 
  summarize(density = mean(larvae_10m2, na.rm=T))

g$lon = as.numeric(unlist(lapply(strsplit(g$station," "), getElement,1)))
g$lat = as.numeric(unlist(lapply(strsplit(g$station," "), getElement,2)))

d = g
return(d)
}

#btl = info('siocalcofiHydroBottle')
#chl = tabledap(info('siocalcofiHydroCasts'), fields = c('month','longitude', 'latitude', 'sta_id', 'sta_code', 'st_station','st_line','year'))

# start with lanternfishes
#td = td[td$common_name==sort(unique(td$common_name))[234],]
#td = td[td$year%in%c(1957:1966) & td$month%in%c(4),]

sardine = subsetCalcofi(calcofi, SPP=330, YEARS = 1951:1966, MONTHS=4)

ggplot(sardine, aes(lon, lat, color=(density))) + geom_point(alpha=0.3) + facet_wrap(~year)

```

# Prep data for input to STAN

```{r prep_data}
nKnots = 30
nLocs = nrow(d)
locs = cbind(as.numeric(d$lon),as.numeric(d$lat))

# cluster analysis to determine knot locations
knots = jitter(pam(locs,nKnots)$medoids)
distKnots = as.matrix(dist(knots))
distKnotsSq = distKnots^2 # squared distances
  
# Calculate distance from knots to grid
distAll = as.matrix(dist(rbind(locs, knots)))^2
# this is the transpose of the lower left corner
distKnots21Sq = t(distAll[-c(1:nLocs), -c((nLocs+1):ncol(distAll))])

Y = as.numeric(d$density)
yearID = as.numeric(as.factor(d$year))
stationID = seq(1,nrow(d))

# create list for STAN
spatglm_data = list("nKnots"=nKnots, "nLocs"=nLocs, "nT" = length(unique(yearID)), "N" = length(Y), "stationID" = stationID, "yearID" = yearID, "y" = Y, "distKnotsSq" = distKnotsSq, "distKnots21Sq" = distKnots21Sq)
spatglm_pars = c("scaledf","yearEffects", "CV")

# estimate model. This model is modified from the simulation model by (1) including indices to allow NAs in the inputted data, and (2) including estimated year effects (intercepts)
stanMod_gamma = stan(file = 'stan_models/mvtGamma_estSigma_index_yr.stan',data = spatglm_data, 
verbose = TRUE, chains = 3, thin = 1, warmup = 100, iter = 200, pars = spatglm_pars)

yearEff_gamma = extract(stanMod_gamma)[["yearEffects"]]

spatglm_pars = c("yearEffects", "gammaA")
stanMod_normal = stan(file = 'simulationTesting/mvnGamma_estSigma_index.stan',data = spatglm_data, 
verbose = TRUE, chains = 3, thin = 1, warmup = 300, iter = 600, pars = spatglm_pars)
yearEff_normal = extract(stanMod_normal)[["yearEffects"]]
```

```{r}
df_gamma = data.frame("year"=1998:2011, "mean" = apply(yearEff_gamma,2,mean), "lo" = apply(yearEff_gamma,2,quantile,0.025),
  "hi" = apply(yearEff_gamma,2,quantile,0.975), group="gamma")
df_normal = data.frame("year"=1998:2011, "mean" = apply(yearEff_normal,2,mean), "lo" = apply(yearEff_normal,2,quantile,0.025),
  "hi" = apply(yearEff_normal,2,quantile,0.975), group="normal")

ggplot(rbind(df_gamma,df_normal), aes(year, mean, group=group, color=group)) + geom_ribbon(aes(ymin = lo, ymax = hi), alpha=0.3)
```


  
