---
title: "Comparing MVN and MVT spatial random effects"
output:
  pdf_document:
    fig_caption: yes
---

# This is an example using oxygen data from the coast of Washington in the trawl survey -- index of hypoxia, etc. 

Recent paper by keller et al. here:
http://onlinelibrary.wiley.com/doi/10.1111/fog.12100/abstract

```{r chunkSet, cache=FALSE, echo=FALSE,warning=FALSE,message=FALSE,results="hide"}
library(cluster)
library(mvtnorm)
library(R2jags)
library(fields)
library(ggplot2)
library(knitr)
library(MASS)
library(rstan)
library(reshape2)
opts_chunk$set(tidy=TRUE, message=FALSE,warning=FALSE)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

```{r}
d = read.csv("crabs/data/TrawlHaulChars_since2002.csv")
d = d[which(is.na(d$o2_at_gear_ml_per_l_der)==FALSE & d$date_dim.year > 2008),]
d = d[,c("haul_latitude_dim.latitude_in_degrees","haul_longitude_dim.longitude_in_degrees","date_dim.year","o2_at_gear_ml_per_l_der","seafloor_depth_m_der")]

d$year = as.numeric(d$date_dim.year)

d = d[which(d$haul_latitude_dim.latitude_in_degrees > 46.260987),]
#which(locs[,2] < 46.260987 & locs[,2] > 41.99)
# only use data from WA coast

ggplot(d, aes(haul_longitude_dim.longitude_in_degrees, haul_latitude_dim.latitude_in_degrees, color=o2_at_gear_ml_per_l_der)) + geom_point() + facet_wrap(~year)

#library(mgcv)
#g = gam(log(o2_at_gear_ml_per_l_der) ~ #te(haul_longitude_dim.longitude_in_degrees, #haul_latitude_dim.latitude_in_degrees), data=d)
```

# Prep data for input to STAN

```{r prep_data}
nKnots = 30
nLocs = nrow(d)
locs = cbind(d$haul_longitude_dim.longitude_in_degrees, d$haul_latitude_dim.latitude_in_degrees)

# cluster analysis to determine knot locations
knots = jitter(pam(locs,nKnots)$medoids)
distKnots = as.matrix(dist(knots))
distKnotsSq = distKnots^2 # squared distances

plot(locs)
points(knots, col='red')
  
# Calculate distance from knots to grid
distAll = as.matrix(dist(rbind(locs, knots)))^2
# this is the transpose of the lower left corner
distKnots21Sq = t(distAll[-c(1:nLocs), -c((nLocs+1):ncol(distAll))])

# convert data format to wide
#d$stationID = seq(1,nrow(d))
#dmelt <- melt(d[,c("year","density","stationID")], 
#  id.vars = c("year", "density","stationID"))
#Y <- dcast(dmelt, year ~ stationID, value.var = "density")

Y = d$o2_at_gear_ml_per_l_der
yearID = as.numeric(as.factor(d$year))
stationID = seq(1,nrow(d))
cov = log(d$seafloor_depth_m_der)
  
# create list for STAN
spatglm_data = list("nKnots"=nKnots, "nLocs"=nLocs, "nT" = length(unique(yearID)), "N" = length(Y), "stationID" = stationID, "yearID" = yearID, "y" = Y, "distKnotsSq" = distKnotsSq, "distKnots21Sq" = distKnots21Sq, "x"=cov)
spatglm_pars = c("scaledf","yearEffects", "CV", "gp_sigmaSq", "gp_scale", "year_sigma","ar","B","spatialEffectsKnots")

# estimate model. This model is modified from the simulation model by (1) including indices to allow NAs in the inputted data, and (2) including estimated year effects (intercepts)
stanMod_gamma = stan(file = 'stan_models/mvtGamma_estSigma_index_cov_yr_ar1.stan',data = spatglm_data, 
verbose = TRUE, chains = 3, thin = 1, warmup = 1000, iter = 2000, pars = spatglm_pars)

save.image("examples/WC_oxygen/stanMod_gamma.Rdata")

spatglm_pars = c("yearEffects", "CV", "gp_sigmaSq", "gp_scale", "year_sigma","ar","B","spatialEffectsKnots")

stanMod_normal = stan(file = 'stan_models/mvnGamma_estSigma_index_cov_yr_ar1.stan',data = spatglm_data, 
verbose = TRUE, chains = 3, thin = 1, warmup = 1000, iter = 2000, pars = spatglm_pars)

save.image("examples/WC_oxygen/stanMod_gamma.Rdata")
```

```{r}
df_gamma = data.frame("year"=1998:2011, "mean" = apply(yearEff_gamma,2,mean), "lo" = apply(yearEff_gamma,2,quantile,0.025),
  "hi" = apply(yearEff_gamma,2,quantile,0.975), group="gamma")
df_normal = data.frame("year"=1998:2011, "mean" = apply(yearEff_normal,2,mean), "lo" = apply(yearEff_normal,2,quantile,0.025),
  "hi" = apply(yearEff_normal,2,quantile,0.975), group="normal")

ggplot(rbind(df_gamma,df_normal), aes(year, mean, group=group, color=group)) + geom_ribbon(aes(ymin = lo, ymax = hi), alpha=0.3)
```


  
