---
title: "Spatiotemporal GLMs"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
---


```{r set-knitr-options, cache=FALSE, echo=FALSE}
library("knitr")
opts_chunk$set(message=FALSE, fig.width=7, fig.height=5, cache = FALSE, autodep = TRUE)
```

```{r}
library(rrfields)
library(dplyr)
library(ggplot2)
library(rstan)
library(bayesplot)
```

Let's initialize some argument and parameter values that we will use throughout.

```{r setup}
options(mc.cores = parallel::detectCores())
ITER <- 600
CHAINS <- 2
SEED <- 1
gp_sigma <- 0.3
sigma <- 0.2
df <- 2
gp_scale <- 1.2
n_draws <- 1
nknots <- 12
```

Let's simulate some data that has heavy tails. 

```{r simulate-data}
set.seed(SEED)
N <- 200
temperature <- rnorm(N, 0, 1)
X <- cbind(1, temperature)
s <- sim_rrfield(df = 1000, n_draws = 1, gp_scale = 2, n_data_points = 200,
  gp_sigma = 0.3, sd_obs = 0.2, n_knots = 15, obs_error = "gamma",
  X = X, B = c(0.5, 0.2)
  )
d <- s$dat
d$temperature <- temperature
ggplot(s$dat, aes(lon, lat, colour = y)) + viridis::scale_colour_viridis() +
  geom_point(size = 3)
```


```{r}
m <- rrfield(y ~ temperature, data = d, obs_error = "gamma", time = "time", station = "station_id",
    lat = "lat", lon = "lon", estimate_df = FALSE, nknots = 15, iter = 600, 
  fixed_df_value = 1000)
```

```{r}
p <- predict(m)
print(m)
plot(m)
```


