---
title: "Comparing MVN and MVT spatial random effects"
output:
  pdf_document:
    fig_caption: yes
---

# This isn't working yet -- in hindsight this dataset may not be large enough. MVT-gamma model seems to converge, MVN-gamma does not? 

```{r chunkSet, cache=FALSE, echo=FALSE,warning=FALSE,message=FALSE,results="hide"}
library(cluster)
library(mvtnorm)
library(R2jags)
library(fields)
library(ggplot2)
library(knitr)
library(MASS)
library(rstan)
library(reshape2)
opts_chunk$set(tidy=TRUE, message=FALSE,warning=FALSE)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

```{r}
chl = read.csv("examples/cclter/Chlorophyll (Process Cruise).csv")
event = read.csv("examples/cclter/CTD Cast Log (Process Cruise).csv")

chl = dplyr::left_join(chl, event)
# start with most common spp, Oithona.spinirostris
# background on biology: http://plankt.oxfordjournals.org/content/38/3/703.short?rss=1
#d = d[,c("cruiseID","dateTime","stationID","consecStationNum","lat","lon","sonicDepth","towDepth","gear","ringDiam","meshSize","towType","AF.Animalia.Arthropoda.Crustacea.Maxillopoda.Copepoda.Neocopepoda.Cyclopoida.N.A.N.A.Oithonidae.Oithona.similis")]
#names(d)[which(names(d)%in%c("AF.Animalia.Arthropoda.Crustacea.Maxillopoda.Copepoda.Neocopepoda.Cyclopoida.N.A.N.A.Oithonidae.Oithona.similis"))] = "density"

chl$month = substr(chl$Datetime.GMT, 6,7)
chl$year = substr(chl$Datetime.GMT, 1,4)

d = chl[,c("month","year","Latitude..º.","Longitude..º.","Chlorophyll.a..µg.l.")]
names(d)[which(names(d)%in%c("Chlorophyll.a..µg.l."))] = "density"
d = d[which(d$density > 0),]

d = d[-which(is.na(d$Longitude..º. + d$Latitude..º.)),]
```

# Prep data for input to STAN

```{r prep_data}
nKnots = 30
nLocs = nrow(d)
locs = cbind(d[,4], d[,3])

# cluster analysis to determine knot locations
knots = jitter(pam(locs,nKnots)$medoids)
distKnots = as.matrix(dist(knots))
distKnotsSq = distKnots^2 # squared distances
  
# Calculate distance from knots to grid
distAll = as.matrix(dist(rbind(locs, knots)))^2
# this is the transpose of the lower left corner
distKnots21Sq = t(distAll[-c(1:nLocs), -c((nLocs+1):ncol(distAll))])

# convert data format to wide
#d$stationID = seq(1,nrow(d))
#dmelt <- melt(d[,c("year","density","stationID")], 
#  id.vars = c("year", "density","stationID"))
#Y <- dcast(dmelt, year ~ stationID, value.var = "density")

Y = d$density
yearID = as.numeric(as.factor(d$year))
stationID = seq(1,nrow(d))

# create list for STAN
spatglm_data = list("nKnots"=nKnots, "nLocs"=nLocs, "nT" = length(unique(yearID)), "N" = length(Y), "stationID" = stationID, "yearID" = yearID, "y" = Y, "distKnotsSq" = distKnotsSq, "distKnots21Sq" = distKnots21Sq)
spatglm_pars = c("scaledf","yearEffects", "CV")

# estimate model. This model is modified from the simulation model by (1) including indices to allow NAs in the inputted data, and (2) including estimated year effects (intercepts)
stanMod_gamma = stan(file = 'simulationTesting/mvtGamma_estSigma_index.stan',data = spatglm_data, 
verbose = TRUE, chains = 3, thin = 1, warmup = 300, iter = 600, pars = spatglm_pars)

yearEff_gamma = extract(stanMod_gamma)[["yearEffects"]]

spatglm_pars = c("yearEffects", "gammaA")
stanMod_normal = stan(file = 'simulationTesting/mvnGamma_estSigma_index.stan',data = spatglm_data, 
verbose = TRUE, chains = 3, thin = 1, warmup = 300, iter = 600, pars = spatglm_pars)
yearEff_normal = extract(stanMod_normal)[["yearEffects"]]
```

```{r}
df_gamma = data.frame("year"=1998:2011, "mean" = apply(yearEff_gamma,2,mean), "lo" = apply(yearEff_gamma,2,quantile,0.025),
  "hi" = apply(yearEff_gamma,2,quantile,0.975), group="gamma")
df_normal = data.frame("year"=1998:2011, "mean" = apply(yearEff_normal,2,mean), "lo" = apply(yearEff_normal,2,quantile,0.025),
  "hi" = apply(yearEff_normal,2,quantile,0.975), group="normal")

ggplot(rbind(df_gamma,df_normal), aes(year, mean, group=group, color=group)) + geom_ribbon(aes(ymin = lo, ymax = hi), alpha=0.3)
```


  
